export const CHOOSE_CATEGORY_ITEM = 'CHOOSE_CATEGORY_ITEM';
export const ADD_REVIEW = 'ADD_REVIEW';
export const CHOOSE_PRODUCT_ITEM = 'CHOOSE_PRODUCT_ITEM';
export const UPDATE_PRODUCT_RESULT = 'UPDATE_PRODUCT_RESULT';

//Products
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

//Profile
export const FETCH_PROFILE_BEGIN = 'FETCH_PROFILE_BEGIN'
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE'

//username & token//

export const AUTH_SUCCESS = 'AUTH_SUCCESS'