export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const INCREASE_PRODUCT_FROM_CART = 'INCREASE_PRODUCT_FROM_CART';
export const DECREASE_PRODUCT_FROM_CART = 'DECREASE_PRODUCT_FROM_CART';

export const DELETE_PRODUCT_FROM_FAV = 'DELETE_PRODUCT_FROM_FAV';
export const FAVOURITE_PRODUCT_FROM_CART = 'FAVOURITE_PRODUCT_FROM_CART';

export const SETTING_DELIVERY_PAYMENT = 'SETTING_DELIVERY_PAYMENT';
export const SETTING_ADDRESS_PAYMENT = 'SETTING_ADDRESS_PAYMENT';
export const SETTING_CARD_PAYMENT = 'SETTING_CARD_PAYMENT';

export const ORDER_TOTAL_PRICE = 'ORDER_TOTAL_PRICE';